server:
  servlet:
    context-path: /shop

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 19012

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  thymeleaf:
    cache: false